### ISSUE TITLE
Link to notes on recent story aren't working

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/papertrail#46]
http://www.npr.org/blogs/itsallpolitics/2015/04/01/395613897/sorting-fact-from-fiction-from-politics-on-the-indiana-law

Apparently, DocCloud wants to use this as an example on something they're publishing soon.

**Comment by alykat** [comment]
Fixed. The docs needed to have a published URL assigned in Document Cloud. I put in the Paper Trail version.

![image](https://cloud.githubusercontent.com/assets/491318/7461387/d67d7c8e-f277-11e4-8969-5d7f17de5433.png)
