### ISSUE TITLE
Local server does not display styles and templates.js

### ISSUE THREAD

**Issue by jjelosua** [nprapps/papertrail#50]
Looks like a npm install path problem

**Comment by eads** [comment]
Not a huge surprise -- that thing is ancient! Could you try upgrading NPM
dependencies at least to app template versions or just to latest?

On Mon, Jun 6, 2016 at 12:30 PM, Juan Elosua <notifications@github.com>
wrote:

> Looks like a npm install path problem
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/nprapps/papertrail/issues/50>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAmuzGNhouez-FiL2XrwzZA0acJxcXG6ks5qJFk5gaJpZM4IvIQY>
> .
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
